Review
keboola/processor-duckdb pull request #2
Opened 2024-06-19 12:32 UTC by kudj

2024-06-21 09:32 UTC, davidesner commented
@kudj doplnil jsem komenty, shrnu:

- Povolit uzivateli zadavat parametry CSV loadu `filename, skip, timestampformat, dateformat, CSV options (sep, quote), header and columns`
   -  Je to proto, ze ta tabulka vubec nemusi mit manifest a potom uzivatel musi urcit vsechno
- U create table rovnou predat pattern/cestu k souboru misto table definition
- To znamena, ze na zacatku nejde iterovat pres table def ale musi se iterovat pres queries a patterny
- Pri patternu musi user definovat i nazev vystupni tabulky, pkeys atp i u simple modu.
- To jestli je to sliced table nebo tabulka s manifestem a jaky je pattern by se melo urcit pred volanim create_table. Pokud pattern zahrne i nejaky tabulky co manifest maji tak by to shodil na UE (abysme se vyhli komplikacim)

2024-06-21 09:33 UTC, davidesner requested changes
@kudj doplnil jsem komenty, shrnu:

- Povolit uzivateli zadavat parametry CSV loadu `filename, skip, timestampformat, dateformat, CSV options (sep, quote), header and columns`
   -  Je to proto, ze ta tabulka vubec nemusi mit manifest a potom uzivatel musi urcit vsechno
- U create table rovnou predat pattern/cestu k souboru misto table definition
- To znamena, ze na zacatku nejde iterovat pres table def ale musi se iterovat pres queries a patterny
- Pri patternu musi user definovat i nazev vystupni tabulky, pkeys atp i u simple modu.
- To jestli je to sliced table nebo tabulka s manifestem a jaky je pattern by se melo urcit pred volanim create_table. Pokud pattern zahrne i nejaky tabulky co manifest maji tak by to shodil na UE (abysme se vyhli komplikacim)

2024-06-25 13:37 UTC, davidesner requested changes
Dva komenty, jinak super!

2024-06-25 13:37 UTC, davidesner commented on .idea/component-duckdb.iml
@kudj slo by vyhodit ty IDE specific soubory?

2024-06-25 13:37 UTC, davidesner commented on src/component.py
> +        config = dict(temp_directory='/opt/tmp/dbtmp',
Zkousel jsi to bezet v Keboola / GCP? Mozna to neni potreba a bylo to jen java specificky. Pokud tam nechame /opt/ tak ta komponenta musi mit povolenout rootUser featuru jinak to spadne

2024-06-25 13:37 UTC, davidesner commented on src/component.py
> +        if isinstance(q.get("output"), dict):
Jenom kosmeticka ten q.get('output') je zbytecne zduplikovany. A co kdyz ten parametr prejmenujem? Obecne je lepsi to mit explicitne definovany v configuration. To je pro priste.

2024-06-26 05:05 UTC, davidesner approved these changes
lgtm. Jenom tady https://github.com/keboola/processor-duckdb/pull/2/files/c68bbac761a05587e378d66fa17fce12aa0258a8#diff-55d447c5bedb7c9e39ba50bcd9d586650b9e0c4aad9371a2b5b8d9ab58391f52R48 kvuli tomu to bude failovat (v okamziku kdy tam duckdb zacne zapisovat), pokud nezapneme rootUser feature

2024-06-26 06:11 UTC, kudj commented
> lgtm. Jenom tady https://github.com/keboola/processor-duckdb/pull/2/files/c68bbac761a05587e378d66fa17fce12aa0258a8#diff-55d447c5bedb7c9e39ba50bcd9d586650b9e0c4aad9371a2b5b8d9ab58391f52R48 kvuli tomu to bude failovat (v okamziku kdy tam duckdb zacne zapisovat), pokud nezapneme rootUser feature

to jsem změnil v https://github.com/keboola/processor-duckdb/pull/2/commits/0c6727a969a2d589135015a5926571d32468d4b2

2024-06-26 06:12 UTC, merged